name: 'Setup Python with UV'
description: 'Sets up Python with UV package manager and caching'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  cache-key-prefix:
    description: 'Prefix for cache key (e.g., "lint", "test")'
    required: true
    default: 'uv'
  working-directory:
    description: 'Working directory for dependency installation'
    required: false
    default: 'backend'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.local/share/uv
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles(format('{0}/uv.lock', inputs.working-directory)) }}-${{ hashFiles(format('{0}/pyproject.toml', inputs.working-directory)) }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles(format('{0}/uv.lock', inputs.working-directory)) }}-
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        uv sync --dev
